version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ftqc-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ftqc_db
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ftqc-network

volumes:
  postgres_data:

networks:
  ftqc-network:
    driver: bridge
